name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v7
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    
    - name: Install enteromark from bioconda channel
      shell: bash -l {0}
      run: |
        conda config --add channels conda-forge
        conda config --add channels bioconda
        conda create -n enteromark -c conda-forge -c bioconda enteromark python=${{ matrix.python-version }} -y
        conda activate enteromark
    
    - name: Test staphscope help
      shell: bash -l {0}
      run: |
        conda activate enteromark
        enteromark --help
